### PR TITLE
1.2.1

### PR DESCRIPTION
**Pull request by matt-bernhardt**
This will resolve three specific errors that seemed easy and small enough to fix during a morning commute.

### CODE REVIEW

**Comment by matt-bernhardt** [comment]
This hotfix is now ready for a code review. It fixes three specific code problems that were discovered by CodeSniffer:

- All files should end with a blank line (46 files affected)
- Files should not start with whitespace (2 files affected)
- Block comments should not have text on their first line (5 files affected)

I have not deployed this branch anywhere, but am happy to do so if desired.
Code review: @PBruk 
FYI: @darcyduke @frrrances 

@JPrevost I need to ask you at some point about how best to deal with sub branches like the three merged into here, to avoid the merge commits?

**Comment by JPrevost** [comment]
@matt-bernhardt I wrote a long reply here then deleted it before sending as it was getting really complicated and possibly not related to what your concern is about.

In short, I think those merge commits are appropriate for your tiered branches as I understand them but I'd by happy to chat live to discuss them :)

**Comment by matt-bernhardt** [comment]
@JPrevost Thanks - I'm still determining what best practice is for this, and when a merge commit is necessary / or not

**Comment by PBruk** [comment]
New formatting looks good.

**Comment by matt-bernhardt** [comment]
This has been deployed to the Test servers and field verified by @frrrances, in addition to code review by @PBruk . Going to merge and deploy to production.

**Pull request merged**
