### PR TITLE
Adds link for 'in-the-media' page on /News to menu.

### PR DESCRIPTION
**Pull request by PBruk**
Tagging @frrrances for code review: this completes the 2-branch process to create an 'in-the-media' page on /News by adding link to main menu.

### CODE REVIEW

**Comment by frrrances** [comment]
This change looks good! Let's wait until the work on https://github.com/MITLibraries/MITLibraries-news/pull/42 is done before we merge this though.

**Comment by frrrances** [comment]
The other branch has merged so this is ready to go. @matt-bernhardt Can you advise on whether it's ok to merge this to 1.4.0 for the next release?

**Comment by matt-bernhardt** [comment]
That earlier branch has indeed been merged, but looking over this PR I'm curious why we are hard-coding the menu contents into the theme source code? This seems like it would slow down future changes in cases where the menu needs to change again.

Is there a reason I'm missing for why the theme wouldn't provide a slot for a user-defined menu?

**Comment by frrrances** [comment]
@matt-bernhardt I'm not sure I'm following - this should be the change to the site header below exhibits:

add-menu-item

Should this be done another way?

**Comment by matt-bernhardt** [comment]
Oh, I see now. I was confused about what menu is affected by this change.
Nevermind - looks good to me.

**Pull request merged**
