### PR TITLE
Restructure theme linting and automated analysis

### PR DESCRIPTION
**Pull request by matt-bernhardt**
## Status
_Use labels (`review needed`, `in progress`, or `paused`) to declare status_

#### What does this PR do?
This tries to restructure our testing/linting setup, along the lines of our discussion this morning (captured in NTI-463). Essentially:

1. Travis failures should be show-stoppers. This checks for security flaws, and syntax errors that would break page rendering.
2. CodeClimate is more thorough, including code linters and style assessments. These should be resolved generally, but there is room for discussion between the developer and reviewer.

Additionally, I reviewed the Travis integration and updated a few related items:
* Removed PHP 5.6 from our list of environments (since the new server stack is confirmed to be 7.1)
* Added the nightly build of PHP (future-proofing)
* Updated the WordPress version loaded from 4.8 to 4.9 and 5.0
* Removed mention of non-multisite WordPres
* Added a conditional check to run PHPCS only for newer PHP version (the latest versions of PHPCS don't run on PHP 5.3)

#### How can a reviewer manually see the effects of these changes?
This is a tooling change, so no effect will be seen outside of GitHub/Travis/CodeClimate.

#### What are the relevant tickets?
- https://mitlibraries.atlassian.net/browse/NTI-463

#### Requires new or updated plugins, themes, or libraries?
NO

#### Requires change to deploy process?
NO

### CODE REVIEW

**Comment by matt-bernhardt** [comment]
The heart of this is the reconfigured PHPCS configuration file, renamed now to `codesniffer.mitlib.xml`. This takes the standard WordPress coding standards, and implements _only_ the following sections:

```
WordPress.CSRF.NonceVerification
WordPress.Security.EscapeOutput
WordPress.Security.NonceVerification
WordPress.Security.PluginMenuSlug
WordPress.Security.SafeRedirect
WordPress.Security.ValidatedSanitizedInput
WordPress.XSS.EscapeOutput
```

The list of things I've turned off is quite long, across five sources:
```
Generic (37 sniffs)
-------------------
  Generic.Classes.DuplicateClassName
  Generic.Classes.OpeningBraceSameLine
  Generic.CodeAnalysis.EmptyStatement
  Generic.CodeAnalysis.ForLoopShouldBeWhileLoop
  Generic.CodeAnalysis.ForLoopWithTestFunctionCall
  Generic.CodeAnalysis.JumbledIncrementer
  Generic.CodeAnalysis.UnconditionalIfStatement
  Generic.CodeAnalysis.UnnecessaryFinalModifier
  Generic.CodeAnalysis.UselessOverridingMethod
  Generic.Commenting.DocComment
  Generic.Commenting.Fixme
  Generic.Commenting.Todo
  Generic.ControlStructures.InlineControlStructure
  Generic.Files.ByteOrderMark
  Generic.Files.EndFileNewline
  Generic.Files.LineEndings
  Generic.Files.OneClassPerFile
  Generic.Files.OneInterfacePerFile
  Generic.Files.OneTraitPerFile
  Generic.Formatting.DisallowMultipleStatements
  Generic.Formatting.MultipleStatementAlignment
  Generic.Formatting.SpaceAfterCast
  Generic.Functions.CallTimePassByReference
  Generic.Functions.FunctionCallArgumentSpacing
  Generic.Functions.OpeningFunctionBraceKernighanRitchie
  Generic.NamingConventions.UpperCaseConstantName
  Generic.PHP.BacktickOperator
  Generic.PHP.DeprecatedFunctions
  Generic.PHP.DisallowAlternativePHPTags
  Generic.PHP.DisallowShortOpenTag
  Generic.PHP.ForbiddenFunctions
  Generic.PHP.LowerCaseConstant
  Generic.PHP.LowerCaseKeyword
  Generic.PHP.Syntax
  Generic.Strings.UnnecessaryStringConcat
  Generic.WhiteSpace.DisallowSpaceIndent
  Generic.WhiteSpace.ScopeIndent

PEAR (3 sniffs)
---------------
  PEAR.Files.IncludingFile
  PEAR.Functions.FunctionCallSignature
  PEAR.NamingConventions.ValidClassName

PSR2 (5 sniffs)
---------------
  PSR2.ControlStructures.ElseIfDeclaration
  PSR2.ControlStructures.SwitchDeclaration
  PSR2.Files.ClosingTag
  PSR2.Methods.MethodDeclaration
  PSR2.Namespaces.NamespaceDeclaration

Squiz (31 sniffs)
-----------------
  Squiz.Classes.SelfMemberReference
  Squiz.Commenting.BlockComment
  Squiz.Commenting.ClassComment
  Squiz.Commenting.ClosingDeclarationComment
  Squiz.Commenting.DocCommentAlignment
  Squiz.Commenting.EmptyCatchComment
  Squiz.Commenting.FileComment
  Squiz.Commenting.FunctionComment
  Squiz.Commenting.FunctionCommentThrowTag
  Squiz.Commenting.InlineComment
  Squiz.Commenting.VariableComment
  Squiz.ControlStructures.ControlSignature
  Squiz.Functions.FunctionDeclarationArgumentSpacing
  Squiz.Functions.FunctionDuplicateArgument
  Squiz.Operators.IncrementDecrementUsage
  Squiz.Operators.ValidLogicalOperators
  Squiz.PHP.CommentedOutCode
  Squiz.PHP.DisallowMultipleAssignments
  Squiz.PHP.DisallowSizeFunctionsInLoops
  Squiz.PHP.EmbeddedPhp
  Squiz.PHP.Eval
  Squiz.PHP.NonExecutableCode
  Squiz.Scope.MemberVarScope
  Squiz.Scope.MethodScope
  Squiz.Strings.ConcatenationSpacing
  Squiz.Strings.DoubleQuoteUsage
  Squiz.WhiteSpace.CastSpacing
  Squiz.WhiteSpace.LanguageConstructSpacing
  Squiz.WhiteSpace.ObjectOperatorSpacing
  Squiz.WhiteSpace.ScopeKeywordSpacing
  Squiz.WhiteSpace.SuperfluousWhitespace

WordPress (70 sniffs)
---------------------
  WordPress.Arrays.ArrayAssignmentRestrictions
  WordPress.Arrays.ArrayDeclaration
  WordPress.Arrays.ArrayDeclarationSpacing
  WordPress.Arrays.ArrayIndentation
  WordPress.Arrays.ArrayKeySpacingRestrictions
  WordPress.Arrays.CommaAfterArrayItem
  WordPress.Arrays.MultipleStatementAlignment
  WordPress.Classes.ClassInstantiation
  WordPress.CodeAnalysis.AssignmentInCondition
  WordPress.CodeAnalysis.EmptyStatement
  WordPress.DB.DirectDatabaseQuery
  WordPress.DB.PreparedSQL
  WordPress.DB.PreparedSQLPlaceholders
  WordPress.DB.RestrictedClasses
  WordPress.DB.RestrictedFunctions
  WordPress.DB.SlowDBQuery
  WordPress.Files.FileName
  WordPress.Functions.DontExtract
  WordPress.Functions.FunctionCallSignatureNoParams
  WordPress.Functions.FunctionRestrictions
  WordPress.NamingConventions.PrefixAllGlobals
  WordPress.NamingConventions.ValidFunctionName
  WordPress.NamingConventions.ValidHookName
  WordPress.NamingConventions.ValidVariableName
  WordPress.PHP.DevelopmentFunctions
  WordPress.PHP.DiscourageGoto
  WordPress.PHP.DiscouragedFunctions
  WordPress.PHP.DiscouragedPHPFunctions
  WordPress.PHP.DontExtract
  WordPress.PHP.NoSilencedErrors
  WordPress.PHP.POSIXFunctions
  WordPress.PHP.PregQuoteDelimiter
  WordPress.PHP.RestrictedPHPFunctions
  WordPress.PHP.StrictComparisons
  WordPress.PHP.StrictInArray
  WordPress.PHP.TypeCasts
  WordPress.PHP.YodaConditions
  WordPress.Utils.I18nTextDomainFixer
  WordPress.Variables.GlobalVariables
  WordPress.Variables.VariableRestrictions
  WordPress.WP.AlternativeFunctions
  WordPress.WP.CapitalPDangit
  WordPress.WP.CronInterval
  WordPress.WP.DeprecatedClasses
  WordPress.WP.DeprecatedFunctions
  WordPress.WP.DeprecatedParameterValues
  WordPress.WP.DeprecatedParameters
  WordPress.WP.DiscouragedConstants
  WordPress.WP.DiscouragedFunctions
  WordPress.WP.EnqueuedResourceParameters
  WordPress.WP.EnqueuedResources
  WordPress.WP.GlobalVariablesOverride
  WordPress.WP.I18n
  WordPress.WP.PostsPerPage
  WordPress.WP.PreparedSQL
  WordPress.WP.TimezoneChange
  WordPress.WhiteSpace.ArbitraryParenthesesSpacing
  WordPress.WhiteSpace.CastStructureSpacing
  WordPress.WhiteSpace.ControlStructureSpacing
  WordPress.WhiteSpace.DisallowInlineTabs
  WordPress.WhiteSpace.OperatorSpacing
  WordPress.WhiteSpace.PrecisionAlignment
  WordPress.WhiteSpace.SemicolonSpacing
```

All of this should be run by CodeClimate, which uses both PHPCS and PHPMD for analysis. We also expect that developers are going to run PHPCS locally, and have added information to this effect to the readme (along with a sample command to do so)

**Comment by matt-bernhardt** [comment]
I should mention that these two pages were pretty useful in assembling this:
https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage
https://github.com/squizlabs/PHP_CodeSniffer/wiki/Annotated-Ruleset

**Comment by matt-bernhardt** [comment]
Okay, this is _finally_ ready for review. Please ask any questions you'd like.

We can also decide to hold this branch open until we fix the flagged security problems - or we can merge this now and do that work soon. Regardless, I"m going to set up these branches for our other themes.

**Comment by frrrances** [comment]
Also thanks for the good comments on the PR! Really useful context - we might want to gather that in the repo wiki (or somewhere...)

**Comment by matt-bernhardt** [comment]
Yeah, I'll set up a PR in our developer documentation to add this information.

**Pull request merged**
