### PR TITLE
Adjusts front page news cards, and monitoring page

### LINKED ISSUE #155: News cards need to be updated to reflect spotlight categories
The change in MITLibraries/MITlibraries-news#66 has exposed a problem in `lib/news.php`

### PR DESCRIPTION
**Pull request by matt-bernhardt**
This _will_ be the branch that fixes #155

### CODE REVIEW

**Comment by matt-bernhardt** [comment]
One problem I'm running into here is that the label of the custom field appears to be inaccessible at the template level. The documentation for ACF seems to be incorrect on this point (or maybe a plugin update would be needed).

The field is defined as key/value pairs:
```
check : Check it out
collection : Featured collection
exhibit : Featured exhibit
service : Featured service
story : Featured story
video : Featured video
media : In the media
tip : Tip
update : Update
```
However, only the key is accessible. All attempts to bull the label per documentation at https://www.advancedcustomfields.com/resources/select/ have failed thus far. Which means, effectively, that we have one value that's usable to drive both the icon and text display.

We could, as @frrrances recommends, use that single value as a CSS class that loads the relevant icons. If we load all possible icons into the stylesheet this is pretty robust - but still would require a redeploy to add new icons, or update icons.

Such a change would probably need to be done across both Parent and News themes - so for now I've replicated something like the news approach and just loaded expected values into `lib/news.php`

@frrrances can we discuss tomorrow at some point?

**Comment by frrrances** [comment]
@matt-bernhardt Sure - I'll come find you this afternoon.

**Comment by matt-bernhardt** [comment]
Okay, this branch should now be ready for code review from @frrrances

**Comment by frrrances** [comment]
Do we need the divs with nothing in them? Otherwise, looks good. 👍

**Comment by matt-bernhardt** [comment]
You know, we probably don't - now that I remember what @hartmans7 told me about the icons. I'll remove them.

**Pull request merged**
