### PR TITLE
Phillip/67 add hidden context to search nav

### LINKED ISSUE #67: Add hidden context to Search nav
To help make clear that the "Search" item in the main nav is a navigation menu, add hidden but accessible text to the nav: 

Reads: "Search navigation menu"
Displays: "Search" (no change from current"
Code: ``<a class="no-underline" href="/search">Search <span class="sr">navigation menu</span></a>``

(actual class for navigation should be whatever we are currently using to hide text meant for screen readers)

### PR DESCRIPTION
**Pull request by PBruk**
Tagging @frrrances for code review: added hidden context to search link in navigation bar and clarified styling used to do so. Fixes #67

### CODE REVIEW

**Comment by matt-bernhardt** [comment]
This shouldn't be merged into `prod` but `1.4.0`

**Comment by frrrances** [comment]
@matt-bernhardt - since we are releasing 1.4.0 this week, should this be part of the next release instead? (that's what i was thinking...)

**Comment by matt-bernhardt** [comment]
We can push this off, sure - in which case this would be merged into the yet-to-be-created `1.5.0`

**Comment by matt-bernhardt** [comment]
Closing in anticipation of re-opening against 1.5.0

**Pull request closed without merging**
