### PR TITLE
Removes forms javascript to interact with ldaplookup.cgi

### PR DESCRIPTION
**Pull request by matt-bernhardt**
## Status
_Use labels (`review needed`, `in progress`, or `paused`) to declare status_

#### What does this PR do?
This removes the trio of javascript files that were added as part of the forms consolidation. It also removes some of the custom code from the Forms and Authenticate template, as well as a function in functions.php that was called by those two tempaltes. There are two reasons for these changes:

1. We have decided to stop using the "look me up in MIT" button functionality that invoked these scripts. That function, which consulted an LDAP lookup script and stashed the results in a user cookie, was conflicting with browser caches that users have already populated - which resulted in a poor user experience when the values were written into the form after users had started filling it out.

2. The LDAP lookup script itself was problematic, and has been removed.

#### Helpful background context (if appropriate)

The removed code was split into the current structure in #254, and had been added back in #233 from being outside of this theme.

#### How can a reviewer manually see the effects of these changes?

Check the staging site, loading forms and looking for any missing functionality. There should also now not be a console warning about a missing ldap lookup. Compare secure forms on stage server to the secure forms on the production server, and note differences in the console.

#### What are the relevant tickets?
- https://mitlibraries.atlassian.net/browse/NTI-507

#### Todo:
- [ ] Documentation
- [ ] Stakeholder approval

#### Requires new or updated plugins, themes, or libraries?
NO - but some bespoke javascript has been removed

#### Requires change to deploy process?
NO

### CODE REVIEW

**Comment by matt-bernhardt** [comment]
@frrrances these are my questions (which may also involve Darcy or others from UX)

1. This removes basically all of the forms integrations in the parent theme. The forms still work, and would still use the Forms template, but this removes basically everything special about that template. It also guts the Authenticate template, which I believe is no longer used with these changes. Is this an appropriately-scaled change?

1. Given that this guts the Authenticate template (which is where the cookie was written coming back from the authentication process), should we just remove this template entirely (and set the corresponding page content to use a default template)?

1. I need to make one tweak to make CodeClimate happy, and somehow also dig up the work that I swear I did to make Travis run again. I'm not sure where that branch went - maybe it wasn't on this repo, but that would surprise me. Are we comfortable merging this with Travis failing?

**Comment by frrrances** [comment]
@matt-bernhardt  These code changes look good but I'd like to check with Darcy before moving forward. 

In answer to your questions: 
1. It makes sense that if we aren't getting info that requires auth, we wouldn't need a page for doing that. Was it doing anything else like keeping the forms behind a login and away from spam?
2. Yes, if there is nothing special about it, let's remove it. 
3. It would be good to get a green check, but not worth a lot of time if we didn't have one previously. Let me know if you want to talk this over...

**Comment by matt-bernhardt** [comment]
The latest on these three issues...

1. (scoping of changes) - at this point, the only difference that I can see between the Forms template and the Default template is that Forms includes a javascript call to submit a Google Analytics event on form submission. This might be something that we can do via another way, however.

Also, while the structure of the two page templates is nearly the same, they differ in code formatting and order of operations - but those changes are more confusing than clarifying, so I'm tempted to refactor things a bit.

2. (authenticate template) - I'll append a commit to remove this template. I looked through the staging site content and found no other content that was using this template.

3. (CodeClimate violation) - this may have been fixed by the time you saw the PR. It was a really small and easy tweak.

**Comment by darcyduke** [comment]
Yay, goodbye!

D

**Pull request merged**
