### PR TITLE
Tweaks Search JS; closes #33

### LINKED ISSUE #33: Send Owens/SFX search traffic to HTTPS
With Rich making good progress on securing Owens, we should be able to send search traffic there via HTTPS encryption:

https://github.com/MITLibraries/MITlibraries-parent/blob/prod/js/search.js#L396

### PR DESCRIPTION
**Pull request by matt-bernhardt**
Big win here is closing #33 and sending Vera search traffic over HTTPS
This also does a small bit of code cleaning per CodeClimate to the file.

Re-factoring is still needed, but not in scope right now.

### CODE REVIEW

**Comment by matt-bernhardt** [comment]
I think this is ready for code review - have deployed to the dev server and things seem to work okay.
Code review: @PBruk 
FYI: @frrrances @darcyduke

**Comment by PBruk** [comment]
I have checked all the changes made... they look good.

**Comment by matt-bernhardt** [comment]
Great, thanks. I'm going to let @frrrances chime in as well, but hope to rebase and merge this into `1.3.0` later today.

**Comment by frrrances** [comment]
lgtm too. nice clean commits! 👍

**Pull request merged**
